# test

### requete get pour récupérer toutes les randonnées par page de 10 randonnées

GET http://localhost:4000/hikes?page=1
Accept: application/json

### requete get pour récupérer 4 randonnées de maniere aléatoire

GET http://localhost:4000/hikes/random
Accept: application/json

### requete get pour récuperer les randonnée d'un utilisateurs mise en favoris

GET http://localhost:4000/bookmarks/1
Accept: application/json



### Test de la requete update users

PATCH http://localhost:4000/users/1
Content-Type: application/json

{
  "id": 1,
  "nickname": "skylilou",
  "localisation": "En bas de chez moi",
  "email": "skylou@hotmail.fr",
  "password": "Newskylarpass"
}

### Test pour obtenir l'email d'un utilisateur
Get http://localhost:4000/users/1

### Test pour crée un utilisateur avec scrypt (password)
POST http://localhost:4000/users
Content-Type: application/json

{
  "id": 1,
  "nickname": "SkylarzLaStreat2",
  "localisation": "En bas de chez toi3",
  "email": "skyloupi2lou@hotmail.fr",
  "password": "Newskylarpass2"
}