services:
  app:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PGHOST=db
      - PGPORT=5433
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=orando
      - JWT_SECRET=un randonneur aimant la randonnée part sur les sentiers en quête de nature et de belle rencontre
      - EMAIL=noreply.orando@gmail.com
      - EMAIL_PASSWORD=vjvz zvth kjdu axfg
    volumes:
      - .:/usr/src/app
    command: npm start

  db:
    image: postgis/postgis:13-3.1
    ports:
      - '5433:5432'  
    environment:
      - POSTGRES_DB=orando
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d  

volumes:
  pgdata:
